### ISSUE TITLE
UAT Fixes (Part 1)

### ISSUE THREAD

**Issue by dillu24** [SimplyStaking/panic#104]
- The pie chart colour scheme and icons for CRITICAL and ERROR are mixed up. ERROR should be represented by gray/purple in the piechart and the skull icon. The CRITICAL severity should be represented by red in the piechart and a red exclamation mark as icon.

**Comment by Cherrett** [comment]
Make popup selector more wide 
![image](https://user-images.githubusercontent.com/49488952/157068366-7f76def7-d51b-4d46-899c-fb7fde02e954.png)

**Comment by Cherrett** [comment]
Update installer to fix weiwatchers typo

![image](https://user-images.githubusercontent.com/49488952/157199486-a7909a12-7d29-4e8d-821e-1e19f96e5245.png)

**Comment by Cherrett** [comment]
https://github.com/SimplyVC/panic/issues/119 - Done separately

**Comment by itsciccio** [comment]
Part 2 of this ticket has been opened -> [#120 ](https://github.com/SimplyVC/panic/issues/120)
