### ISSUE TITLE
Settings: Sub-chain - delete a sub-chain 4/4

### ISSUE THREAD

**Issue by crsfalzon** [SimplyStaking/panic#228]
### User Story
As a node operator, I want to be able to delete any of my sub-chain setups, so my setup can be adjusted to meet my operational needs.

### Description
The scope of this ticket is the implementation of a delete icon under the Actions column, that will allow the node operator to permanentaly delete the configuration for the selected sub-chain.

![update delete](https://user-images.githubusercontent.com/89395527/171151771-042e9d99-5fac-46d8-87b2-a3d537c03a10.PNG)

### Requirements

- Delete icon under the Actions column (see #225)
- When clicked, this presents the node operator with a confirmation popup. 
- Popup title: Delete Confirmation 
- Body: Are you sure you want to delete your configuration for _Name_? 
- Confirm button - when clicked, deletes the selected configuration
- Cancel button - when clicked, the popup is closed, with no changes to the sub-chain setup

### Blocked by

#225 

### Acceptance criteria

**Scenario**: The node operator is on configuration/sub-chains after having selected Chains from the Settings dropdown https://github.com/SimplyVC/panic/issues/223
**Given**: The node operator wants to delete a sub-chain
**When**: He clicks on the delete icon for a specific sub-chain
**Then**:  Display the delete confirmation popup
**And**: If the user selects the confirm button
**Then**: The deletion of the sub-chain setup proceeds
**And**: If the user selects the cancel button
**Then**: Close the popup

**Comment by dillu24** [comment]
Align actions button in centre

**Comment by dillu24** [comment]
Align table to the top
